FROM ruby:3.4.3

WORKDIR /rails

# Doesn't need node and yarn because this is an api only app
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev postgresql-client git curl

RUN gem install bundler

COPY Gemfile /rails/Gemfile
COPY Gemfile.lock /rails/Gemfile.lock
RUN bundle install

COPY . /rails

EXPOSE 3000

ENV RAILS_ENV=development

CMD ["rails", "server", "-b", "0.0.0.0"]
