FROM ruby:3.4.3

WORKDIR /rails-app

# Doesn't need node and yarn because this is an api only app
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev postgresql-client git curl

COPY Gemfile /rails-app/Gemfile
COPY Gemfile.lock /rails-app/Gemfile.lock
RUN bundle config --delete without
RUN bundle install

COPY . /rails-app

EXPOSE 3000

ENV RAILS_ENV=development

CMD ["rails", "server", "-b", "0.0.0.0"]
